# Generated by Django 3.2.12 on 2022-04-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
