# Generated by Django 3.2.12 on 2022-04-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_alter_appointment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
