# Generated by Django 3.2.12 on 2022-04-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_alter_appointment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='file',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
