# Generated by Django 3.2.12 on 2022-04-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0013_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
