# Generated by Django 3.2.12 on 2022-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0015_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='file',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
