# Generated by Django 3.2.12 on 2022-04-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0016_appointment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='file',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
