# Generated by Django 3.2.12 on 2022-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0017_alter_appointment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created',
            field=models.DateTimeField(default=''),
        ),
    ]
