# Generated by Django 3.2.12 on 2022-04-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0024_formlastactive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormLastActive',
        ),
    ]
