# Generated by Django 3.2.12 on 2022-04-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0025_delete_formlastactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='file',
        ),
    ]
