# Generated by Django 3.2.12 on 2022-04-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0028_appointment1_appointment2_appointment3_appointment4_appointment5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment1',
            new_name='riya',
        ),
    ]
