# Generated by Django 3.2.12 on 2022-04-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0029_rename_appointment1_riya'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment4',
            new_name='himanshi',
        ),
        migrations.RenameModel(
            old_name='Appointment5',
            new_name='james',
        ),
        migrations.RenameModel(
            old_name='Appointment3',
            new_name='john',
        ),
        migrations.RenameModel(
            old_name='Appointment',
            new_name='larry',
        ),
        migrations.RenameModel(
            old_name='Appointment2',
            new_name='sohil',
        ),
    ]
