# Generated by Django 3.2.12 on 2022-04-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0030_auto_20220419_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='james',
            old_name='state',
            new_name='time',
        ),
    ]
