# Generated by Django 3.2.12 on 2022-04-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0031_rename_state_james_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riya',
            old_name='state',
            new_name='time',
        ),
    ]
