# Generated by Django 3.2.12 on 2022-04-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0034_alter_riya_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riya',
            name='time',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
