# Generated by Django 3.2.12 on 2022-04-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0035_alter_riya_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='himanshi',
            name='time',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='john',
            name='time',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='larry',
            name='time',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='sohil',
            name='time',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='james',
            name='time',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
